#!/usr/bin/env python3
"""
Golden regression test: the fast path must reproduce the reference pipeline.

Runs the real region-r1s analysis for comps/paper.bh (tree 0, its four
cluster-growth steps, tree 1, ...) and compares every produced *.tab against
the checked-in golden files, which were generated by the original
(process-per-motif, pure-Python search.v17) implementation.

    micromamba run -n rnamotifs2 python tests/golden_r1s.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(HERE)))

import rnamotifs2

COMPS, REGION, GENOME = "paper.bh", "r1s", "homo_sapiens.ensembl115"
GOLDEN = os.path.join(HERE, "golden")
FLOAT_COLS = {"fisher", "ig", "raw_ig", "p_emp", "specificity"}
ATOL = 1e-9


def read_tab(path):
    with open(path) as f:
        header = f.readline().rstrip("\n").split("\t")
        rows = [dict(zip(header, l.rstrip("\n").split("\t"))) for l in f if l.strip()]
    return header, rows


def compare(name, got_path, want_path):
    if not os.path.exists(got_path):
        return "%s: not produced" % name
    gh, gr = read_tab(got_path)
    wh, wr = read_tab(want_path)
    if gh != wh:
        return "%s: header %s != %s" % (name, gh, wh)
    if len(gr) != len(wr):
        return "%s: %d rows != %d" % (name, len(gr), len(wr))
    for i, (g, w) in enumerate(zip(gr, wr)):
        for col in gh:
            gv, wv = g[col], w[col]
            if col in FLOAT_COLS:
                if abs(float(gv) - float(wv)) > ATOL * max(1.0, abs(float(wv))):
                    return "%s row %d col %s: %s != %s" % (name, i, col, gv, wv)
            elif gv != wv:
                return "%s row %d col %s: %r != %r" % (name, i, col, gv, wv)
    return None


def main():
    rnamotifs2.data.read_config(COMPS)
    rnamotifs2.start(COMPS, REGION, 0, rnamotifs2.data.pth)

    region_folder = os.path.join(rnamotifs2.path.comps_folder, COMPS, REGION)
    golden = sorted(f for f in os.listdir(GOLDEN) if f.startswith("paper.bh.r1s."))
    fail = False
    for gf in golden:
        local = gf[len("paper.bh.r1s."):]
        err = compare(local, os.path.join(region_folder, local), os.path.join(GOLDEN, gf))
        print(("FAIL " + err) if err else ("ok   " + local))
        fail |= err is not None
    sys.exit(1 if fail else 0)


if __name__ == "__main__":
    main()
